[package]
name = "pygmab"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "gmab"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.24.0"
gmab_rust = { package = "gmab", path = "../gmab" }
